# Generated by Django 6.0.2 on 2026-02-07 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangoapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dealership",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=200)),
                ("zip", models.CharField(max_length=20)),
                ("lat", models.CharField(max_length=50)),
                ("long", models.CharField(max_length=50)),
                ("short_name", models.CharField(max_length=50)),
                ("full_name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("review", models.TextField()),
                ("purchase", models.BooleanField()),
                (
                    "purchase_date",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("car_make", models.CharField(blank=True, max_length=50, null=True)),
                ("car_model", models.CharField(blank=True, max_length=50, null=True)),
                ("car_year", models.IntegerField(blank=True, null=True)),
                ("sentiment", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "dealership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="djangoapp.dealership",
                    ),
                ),
            ],
        ),
    ]
